### ISSUE TITLE
geoviqua as it doesn't have schema-ident.xml     

### ISSUE THREAD

**Issue by Delawen** [Delawen/geoviqua-geonetwork-plugin#1]
2014-04-09 10:16:20,382 ERROR [geonetwork.schemamanager] -     Skipping : iso19139.geoviqua as it doesn't have schema-ident.xml  
java.lang.NullPointerException  
        at org.fao.geonet.kernel.SchemaManager.realAddPluginSchema(SchemaManager.java:836)  
        at org.fao.geonet.kernel.SchemaManager.addPluginSchema(SchemaManager.java:248)  
        at org.fao.geonet.services.schema.SchemaUtils.doSchema(SchemaUtils.java:157)  
        at org.fao.geonet.services.schema.SchemaUtils.processSchema(SchemaUtils.java:128)  
        at org.fao.geonet.services.schema.SchemaUtils.addSchema(SchemaUtils.java:51)  
        at org.fao.geonet.services.schema.Add.exec(Add.java:93)  
        at jeeves.server.dispatchers.ServiceInfo.execService(ServiceInfo.java:230)  
        at jeeves.server.dispatchers.ServiceInfo.execServices(ServiceInfo.java:139)  
        at jeeves.server.dispatchers.ServiceManager.dispatch(ServiceManager.java:430)  
        at jeeves.server.dispatchers.ServiceManager.dispatch(ServiceManager.java:362)

**Comment by Delawen** [comment]
This is only using the prepared zip. Using the source code directly does not show this error.
